### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 6.00 GiB total capacity; 1.83 GiB already allocated; 2.49 GiB free; 2.02 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by yinjia823** [babysor/MockingBird#128]
{| Epoch: 1/1 (121/15311) | Loss: 1.719 | 0.73 steps/s | Step: 0k | }Traceback (most recent call last):
出现错误
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 6.00 GiB total capacity; 1.83 GiB already allocated; 2.49 GiB free; 2.02 GiB reserved in total by PyTorch)
显示显存不足
已经修改### Tacotron Training
        tts_schedule = [(2,  1e-3,  10_000,  8),   # Progressive training schedule
                        (2,  5e-4,  15_000,  8),   # (r, lr, step, batch_size)
                        (2,  2e-4,  20_000,  8),   # (r, lr, step, batch_size)
                        (2,  1e-4,  30_000,  8),   #
                        (2,  5e-5,  40_000,  8),   #
                        (2,  1e-5,  60_000,  8),   #
                        (2,  5e-6, 160_000,  8),   # r = reduction factor (# of mel frames
                        (2,  3e-6, 320_000,  8),   #     synthesized for each decoder iteration)
                        (2,  1e-6, 640_000,  8)],  # lr = learning rate

请问我要怎么调整才能继续训练合成器？感谢各位大佬

**Comment by babysor** [comment]
batch_size 6，估计你这个显卡专用显存比较低

**Comment by 851984709** [comment]
有可能是在两个conda环境中都装了pytorch。
我在base里配置完环境后，可以正常运行；但是新建一个环境然后同样再装一个pytorch，训练的时候就会报“CUDA out of memory”。把其中一个装了pytorch的环境删掉就可以了。
